/**
 * Cost computation from token counts × model pricing.
 *
 * TypeScript port of thClaws's `Catalogue::compute_cost_usd` (see
 * `crates/core/src/model_catalogue.rs`). Same decision tree, same
 * rounding, same cache-math: `prompt_tokens` is the FULL prompt
 * (including the cached portion); subtract `cached_input_tokens`
 * to get the uncached new tokens that pay the standard rate.
 *
 * Sources of pricing data, in priority order:
 *   1. In-memory override (set via `setPricingTable` — used by
 *      paperclip-adapter's optional live-refresh from
 *      thClaws's `/v1/models`).
 *   2. Bundled `pricing-fallback.json` — snapshot of the thClaws
 *      catalogue, regenerated by
 *      `scripts/sync-pricing-to-paperclip-adapter.py`.
 *
 * The bundled snapshot lets the adapter compute cost even when not
 * running alongside a live thClaws daemon (CI smoke tests, paperclip
 * standalone, npm-published version used outside our monorepo).
 *
 * See `dev-plan/24-model-catalogue-pricing.md` for the design.
 */

import { PRICING_FALLBACK } from "./pricing-fallback.js";

export interface ModelPricing {
  provider?: string;
  input_per_mtok?: number;
  output_per_mtok?: number;
  cached_input_per_mtok?: number;
  cache_creation_per_mtok?: number;
  reasoning_per_mtok?: number;
  free?: boolean;
  tier_billed?: boolean;
}

export interface PricingTable {
  schema?: number;
  generated_at?: string;
  source?: string;
  models: Record<string, ModelPricing>;
}

export interface TokenUsage {
  /** Total prompt tokens INCLUDING any cached portion. */
  prompt_tokens?: number | null;
  completion_tokens?: number | null;
  /** Subset of `prompt_tokens` that hit a read-cache. */
  cached_input_tokens?: number | null;
  /** New tokens added to the cache this turn (Anthropic only). */
  cache_creation_tokens?: number | null;
  /** OpenAI o1/o3 hidden reasoning tokens (already inside
   *  `completion_tokens` per OpenAI's wire convention). */
  reasoning_tokens?: number | null;
}

let activeTable: PricingTable = PRICING_FALLBACK;

/**
 * Override the in-memory pricing table. Intended for paperclip-adapter's
 * optional live-refresh path (`/v1/models` pull merged on top of
 * bundled snapshot). Pass `null` to revert to the bundled fallback.
 */
export function setPricingTable(table: PricingTable | null): void {
  activeTable = table ?? (PRICING_FALLBACK);
}

/** Lookup pricing for a model id, returning the merged entry or null. */
export function lookupPricing(model: string): ModelPricing | null {
  if (model in activeTable.models) {
    return activeTable.models[model];
  }
  // Vendor-prefix fallback: `openrouter/anthropic/claude-…` falls
  // through to `claude-…` etc. Matches Catalogue::find_entry's
  // prefix-stripping in thClaws.
  let remaining = model;
  while (remaining.includes("/")) {
    remaining = remaining.slice(remaining.indexOf("/") + 1);
    if (remaining in activeTable.models) {
      return activeTable.models[remaining];
    }
  }
  return null;
}

/**
 * Compute USD cost for a single run's token usage.
 *
 * Returns:
 *   - `null` when the model isn't in the catalogue (caller surfaces
 *     "Cost unavailable")
 *   - `null` when the entry is `tier_billed: true` (caller surfaces
 *     "Tier-billed" — per-token math doesn't reflect actual billing)
 *   - `null` when the entry has NO pricing fields (distinct from
 *     "free"; caller surfaces "Pricing not yet curated")
 *   - `0` when the entry is `free: true`
 *   - a positive number otherwise (sum of priced contributions; any
 *     field missing in the entry simply contributes $0 to the sum
 *     — caller can inspect lookupPricing(model) to detect "partial")
 *
 * Cache math: `prompt_tokens` carries the total. Uncached input =
 * `prompt_tokens - cached_input_tokens`. Reasoning tokens (OpenAI
 * o1/o3) are billed at `reasoning_per_mtok` when set, else folded
 * into output via fallback.
 */
export function tokensToCostUsd(
  model: string,
  usage: TokenUsage,
): number | null {
  const entry = lookupPricing(model);
  if (!entry) return null;
  if (entry.tier_billed === true) return null;
  if (entry.free === true) return 0;
  const hasAnyRate =
    entry.input_per_mtok !== undefined ||
    entry.output_per_mtok !== undefined ||
    entry.cached_input_per_mtok !== undefined ||
    entry.cache_creation_per_mtok !== undefined ||
    entry.reasoning_per_mtok !== undefined;
  if (!hasAnyRate) return null;

  const perM = (count: number | null | undefined, rate: number | undefined): number =>
    count && rate ? (count / 1_000_000) * rate : 0;

  const prompt = usage.prompt_tokens ?? 0;
  const cached = usage.cached_input_tokens ?? 0;
  // saturating subtract — guards against a buggy provider sending
  // cached > prompt (the Rust side does the same).
  const uncachedInput = Math.max(0, prompt - cached);

  const uncached = perM(uncachedInput, entry.input_per_mtok);
  // Cache-read falls back to standard input rate when the provider
  // doesn't publish a cache-tier discount (matches OpenAI's gpt-4o
  // case: only Anthropic publishes both rates).
  const cachedCost = perM(
    cached,
    entry.cached_input_per_mtok ?? entry.input_per_mtok,
  );
  const cacheWrite = perM(usage.cache_creation_tokens, entry.cache_creation_per_mtok);
  const output = perM(usage.completion_tokens, entry.output_per_mtok);
  const reasoning = perM(
    usage.reasoning_tokens,
    entry.reasoning_per_mtok ?? entry.output_per_mtok,
  );

  return uncached + cachedCost + cacheWrite + output + reasoning;
}

/**
 * Snapshot metadata for diagnostics — exposed so adapter consumers can
 * log "pricing table source: bundled (generated YYYY-MM-DD)" when
 * computing costs that might be stale.
 */
export function pricingTableMeta(): { source?: string; generated_at?: string } {
  return {
    source: activeTable.source,
    generated_at: activeTable.generated_at,
  };
}
