// Auto-generated by scripts/sync-pricing-to-paperclip-adapter.py.
// Do not hand-edit; re-run the script to refresh from the
// canonical thClaws catalogue (see dev-plan/24 Phase C).

import type { PricingTable } from "./pricing.js";

export const PRICING_FALLBACK: PricingTable = {
  "schema": 1,
  "generated_at": "2026-05-19T00:00:00Z",
  "source": "thclaws/crates/core/resources/model_catalogue.json — synced 2026-05-19 via scripts/sync-pricing-to-paperclip-adapter.py",
  "models": {
    "agent/claude-haiku-4-5": {
      "provider": "anthropic-agent",
      "input_per_mtok": 1.0,
      "output_per_mtok": 5.0,
      "cached_input_per_mtok": 0.1,
      "cache_creation_per_mtok": 1.25
    },
    "agent/claude-haiku-4-5-20251001": {
      "provider": "anthropic-agent",
      "input_per_mtok": 1.0,
      "output_per_mtok": 5.0,
      "cached_input_per_mtok": 0.1,
      "cache_creation_per_mtok": 1.25
    },
    "agent/claude-opus-4-1-20250805": {
      "provider": "anthropic-agent",
      "input_per_mtok": 15.0,
      "output_per_mtok": 75.0,
      "cached_input_per_mtok": 1.5,
      "cache_creation_per_mtok": 18.75
    },
    "agent/claude-opus-4-20250514": {
      "provider": "anthropic-agent",
      "input_per_mtok": 15.0,
      "output_per_mtok": 75.0,
      "cached_input_per_mtok": 1.5,
      "cache_creation_per_mtok": 18.75
    },
    "agent/claude-opus-4-5-20251101": {
      "provider": "anthropic-agent",
      "input_per_mtok": 5.0,
      "output_per_mtok": 25.0,
      "cached_input_per_mtok": 0.5,
      "cache_creation_per_mtok": 6.25
    },
    "agent/claude-opus-4-6": {
      "provider": "anthropic-agent",
      "input_per_mtok": 5.0,
      "output_per_mtok": 25.0,
      "cached_input_per_mtok": 0.5,
      "cache_creation_per_mtok": 6.25
    },
    "agent/claude-opus-4-7": {
      "provider": "anthropic-agent",
      "input_per_mtok": 5.0,
      "output_per_mtok": 25.0,
      "cached_input_per_mtok": 0.5,
      "cache_creation_per_mtok": 6.25
    },
    "agent/claude-sonnet-4-20250514": {
      "provider": "anthropic-agent",
      "input_per_mtok": 3.0,
      "output_per_mtok": 15.0,
      "cached_input_per_mtok": 0.3,
      "cache_creation_per_mtok": 3.75
    },
    "agent/claude-sonnet-4-5": {
      "provider": "anthropic-agent",
      "input_per_mtok": 3.0,
      "output_per_mtok": 15.0,
      "cached_input_per_mtok": 0.3,
      "cache_creation_per_mtok": 3.75
    },
    "agent/claude-sonnet-4-5-20250929": {
      "provider": "anthropic-agent",
      "input_per_mtok": 3.0,
      "output_per_mtok": 15.0,
      "cached_input_per_mtok": 0.3,
      "cache_creation_per_mtok": 3.75
    },
    "agent/claude-sonnet-4-6": {
      "provider": "anthropic-agent",
      "input_per_mtok": 3.0,
      "output_per_mtok": 15.0,
      "cached_input_per_mtok": 0.3,
      "cache_creation_per_mtok": 3.75
    },
    "ai21/jamba-large-1.7": {
      "provider": "openrouter",
      "input_per_mtok": 2.0,
      "output_per_mtok": 8.0,
      "free": false
    },
    "aion-labs/aion-1.0": {
      "provider": "openrouter",
      "free": false
    },
    "aion-labs/aion-1.0-mini": {
      "provider": "openrouter",
      "free": false
    },
    "aion-labs/aion-2.0": {
      "provider": "openrouter",
      "free": false
    },
    "aion-labs/aion-rp-llama-3.1-8b": {
      "provider": "openrouter",
      "free": false
    },
    "alfredpros/codellama-7b-instruct-solidity": {
      "provider": "openrouter",
      "free": false
    },
    "alibaba/tongyi-deepresearch-30b-a3b": {
      "provider": "openrouter",
      "free": false
    },
    "allenai/olmo-3-32b-think": {
      "provider": "openrouter",
      "free": false
    },
    "amazon/nova-2-lite-v1": {
      "provider": "openrouter",
      "free": false
    },
    "amazon/nova-lite-v1": {
      "provider": "openrouter",
      "free": false
    },
    "amazon/nova-micro-v1": {
      "provider": "openrouter",
      "free": false
    },
    "amazon/nova-premier-v1": {
      "provider": "openrouter",
      "free": false
    },
    "amazon/nova-pro-v1": {
      "provider": "openrouter",
      "free": false
    },
    "anthracite-org/magnum-v4-72b": {
      "provider": "openrouter",
      "free": false
    },
    "anthropic/claude-3-haiku": {
      "provider": "openrouter",
      "input_per_mtok": 0.25,
      "output_per_mtok": 1.25,
      "free": false
    },
    "anthropic/claude-3.5-haiku": {
      "provider": "openrouter",
      "free": false
    },
    "anthropic/claude-3.7-sonnet": {
      "provider": "openrouter",
      "input_per_mtok": 3.0,
      "output_per_mtok": 15.0
    },
    "anthropic/claude-haiku-4.5": {
      "provider": "openrouter",
      "input_per_mtok": 1.0,
      "output_per_mtok": 5.0,
      "cached_input_per_mtok": 0.1,
      "cache_creation_per_mtok": 1.25,
      "free": false
    },
    "anthropic/claude-opus-4": {
      "provider": "openrouter",
      "input_per_mtok": 15.0,
      "output_per_mtok": 75.0,
      "cached_input_per_mtok": 1.5,
      "cache_creation_per_mtok": 18.75,
      "free": false
    },
    "anthropic/claude-opus-4.1": {
      "provider": "openrouter",
      "input_per_mtok": 15.0,
      "output_per_mtok": 75.0,
      "cached_input_per_mtok": 1.5,
      "cache_creation_per_mtok": 18.75,
      "free": false
    },
    "anthropic/claude-opus-4.5": {
      "provider": "openrouter",
      "input_per_mtok": 5.0,
      "output_per_mtok": 25.0,
      "cached_input_per_mtok": 0.5,
      "cache_creation_per_mtok": 6.25,
      "free": false
    },
    "anthropic/claude-opus-4.6": {
      "provider": "openrouter",
      "input_per_mtok": 5.0,
      "output_per_mtok": 25.0,
      "cached_input_per_mtok": 0.5,
      "cache_creation_per_mtok": 6.25,
      "free": false
    },
    "anthropic/claude-opus-4.6-fast": {
      "provider": "openrouter",
      "free": false
    },
    "anthropic/claude-opus-4.7": {
      "provider": "openrouter",
      "input_per_mtok": 5.0,
      "output_per_mtok": 25.0,
      "cached_input_per_mtok": 0.5,
      "cache_creation_per_mtok": 6.25,
      "free": false
    },
    "anthropic/claude-opus-4.7-fast": {
      "provider": "openrouter",
      "free": false
    },
    "anthropic/claude-sonnet-4": {
      "provider": "openrouter",
      "input_per_mtok": 3.0,
      "output_per_mtok": 15.0,
      "cached_input_per_mtok": 0.3,
      "cache_creation_per_mtok": 3.75,
      "free": false
    },
    "anthropic/claude-sonnet-4.5": {
      "provider": "openrouter",
      "input_per_mtok": 3.0,
      "output_per_mtok": 15.0,
      "cached_input_per_mtok": 0.3,
      "cache_creation_per_mtok": 3.75,
      "free": false
    },
    "anthropic/claude-sonnet-4.6": {
      "provider": "openrouter",
      "input_per_mtok": 3.0,
      "output_per_mtok": 15.0,
      "cached_input_per_mtok": 0.3,
      "cache_creation_per_mtok": 3.75,
      "free": false
    },
    "arcee-ai/coder-large": {
      "provider": "openrouter",
      "free": false
    },
    "arcee-ai/maestro-reasoning": {
      "provider": "openrouter",
      "free": false
    },
    "arcee-ai/spotlight": {
      "provider": "openrouter",
      "free": false
    },
    "arcee-ai/trinity-large-preview": {
      "provider": "openrouter",
      "free": false
    },
    "arcee-ai/trinity-large-thinking": {
      "provider": "openrouter",
      "free": false
    },
    "arcee-ai/trinity-large-thinking:free": {
      "provider": "openrouter",
      "free": true
    },
    "arcee-ai/trinity-mini": {
      "provider": "openrouter",
      "free": false
    },
    "arcee-ai/virtuoso-large": {
      "provider": "openrouter",
      "free": false
    },
    "baidu/cobuddy:free": {
      "provider": "openrouter",
      "free": true
    },
    "baidu/ernie-4.5-21b-a3b": {
      "provider": "openrouter",
      "free": false
    },
    "baidu/ernie-4.5-21b-a3b-thinking": {
      "provider": "openrouter",
      "free": false
    },
    "baidu/ernie-4.5-300b-a47b": {
      "provider": "openrouter",
      "free": false
    },
    "baidu/ernie-4.5-vl-28b-a3b": {
      "provider": "openrouter",
      "free": false
    },
    "baidu/ernie-4.5-vl-424b-a47b": {
      "provider": "openrouter",
      "free": false
    },
    "baidu/qianfan-ocr-fast:free": {
      "provider": "openrouter",
      "free": true
    },
    "bytedance-seed/seed-1.6": {
      "provider": "openrouter",
      "free": false
    },
    "bytedance-seed/seed-1.6-flash": {
      "provider": "openrouter",
      "free": false
    },
    "bytedance-seed/seed-2.0-lite": {
      "provider": "openrouter",
      "free": false
    },
    "bytedance-seed/seed-2.0-mini": {
      "provider": "openrouter",
      "free": false
    },
    "bytedance/ui-tars-1.5-7b": {
      "provider": "openrouter",
      "input_per_mtok": 0.1,
      "output_per_mtok": 0.2,
      "free": false
    },
    "claude-haiku-4-5": {
      "provider": "anthropic",
      "input_per_mtok": 1.0,
      "output_per_mtok": 5.0,
      "cached_input_per_mtok": 0.1,
      "cache_creation_per_mtok": 1.25
    },
    "claude-haiku-4-5-20251001": {
      "provider": "anthropic",
      "input_per_mtok": 1.0,
      "output_per_mtok": 5.0,
      "cached_input_per_mtok": 0.1,
      "cache_creation_per_mtok": 1.25
    },
    "claude-opus-4-1-20250805": {
      "provider": "anthropic",
      "input_per_mtok": 15.0,
      "output_per_mtok": 75.0,
      "cached_input_per_mtok": 1.5,
      "cache_creation_per_mtok": 18.75
    },
    "claude-opus-4-20250514": {
      "provider": "anthropic",
      "input_per_mtok": 15.0,
      "output_per_mtok": 75.0,
      "cached_input_per_mtok": 1.5,
      "cache_creation_per_mtok": 18.75
    },
    "claude-opus-4-5-20251101": {
      "provider": "anthropic",
      "input_per_mtok": 5.0,
      "output_per_mtok": 25.0,
      "cached_input_per_mtok": 0.5,
      "cache_creation_per_mtok": 6.25
    },
    "claude-opus-4-6": {
      "provider": "anthropic",
      "input_per_mtok": 5.0,
      "output_per_mtok": 25.0,
      "cached_input_per_mtok": 0.5,
      "cache_creation_per_mtok": 6.25
    },
    "claude-opus-4-7": {
      "provider": "anthropic",
      "input_per_mtok": 5.0,
      "output_per_mtok": 25.0,
      "cached_input_per_mtok": 0.5,
      "cache_creation_per_mtok": 6.25
    },
    "claude-sonnet-4-20250514": {
      "provider": "anthropic",
      "input_per_mtok": 3.0,
      "output_per_mtok": 15.0,
      "cached_input_per_mtok": 0.3,
      "cache_creation_per_mtok": 3.75
    },
    "claude-sonnet-4-5": {
      "provider": "anthropic",
      "input_per_mtok": 3.0,
      "output_per_mtok": 15.0,
      "cached_input_per_mtok": 0.3,
      "cache_creation_per_mtok": 3.75
    },
    "claude-sonnet-4-5-20250929": {
      "provider": "anthropic",
      "input_per_mtok": 3.0,
      "output_per_mtok": 15.0,
      "cached_input_per_mtok": 0.3,
      "cache_creation_per_mtok": 3.75
    },
    "claude-sonnet-4-6": {
      "provider": "anthropic",
      "input_per_mtok": 3.0,
      "output_per_mtok": 15.0,
      "cached_input_per_mtok": 0.3,
      "cache_creation_per_mtok": 3.75
    },
    "codex/gpt-5-codex": {
      "provider": "openai-responses",
      "input_per_mtok": 1.25,
      "output_per_mtok": 10.0,
      "cached_input_per_mtok": 0.125
    },
    "codex/gpt-5.1-codex": {
      "provider": "openai-responses",
      "input_per_mtok": 1.25,
      "output_per_mtok": 10.0,
      "cached_input_per_mtok": 0.125
    },
    "codex/gpt-5.2-codex": {
      "provider": "openai-responses",
      "input_per_mtok": 1.75,
      "output_per_mtok": 14.0,
      "cached_input_per_mtok": 0.175
    },
    "cognitivecomputations/dolphin-mistral-24b-venice-edition:free": {
      "provider": "openrouter",
      "free": true
    },
    "cohere/command-a": {
      "provider": "openrouter",
      "free": false
    },
    "cohere/command-r-08-2024": {
      "provider": "openrouter",
      "input_per_mtok": 0.15,
      "output_per_mtok": 0.6,
      "free": false
    },
    "cohere/command-r-plus-08-2024": {
      "provider": "openrouter",
      "input_per_mtok": 2.5,
      "output_per_mtok": 10.0,
      "free": false
    },
    "cohere/command-r7b-12-2024": {
      "provider": "openrouter",
      "input_per_mtok": 0.15,
      "output_per_mtok": 0.0375,
      "free": false
    },
    "dashscope/qwen-max": {
      "provider": "dashscope",
      "input_per_mtok": 1.6,
      "output_per_mtok": 6.4
    },
    "dashscope/qwen-plus": {
      "provider": "dashscope",
      "input_per_mtok": 0.4,
      "output_per_mtok": 1.2
    },
    "dashscope/qwen-plus-2025-01-25": {
      "provider": "dashscope",
      "input_per_mtok": 0.4,
      "output_per_mtok": 1.2
    },
    "dashscope/qwen-plus-2025-04-28": {
      "provider": "dashscope",
      "input_per_mtok": 0.4,
      "output_per_mtok": 1.2
    },
    "dashscope/qwen-plus-2025-07-14": {
      "provider": "dashscope",
      "input_per_mtok": 0.4,
      "output_per_mtok": 1.2
    },
    "dashscope/qwen-turbo": {
      "provider": "dashscope",
      "input_per_mtok": 0.05,
      "output_per_mtok": 0.2
    },
    "dashscope/qwen-turbo-2024-11-01": {
      "provider": "dashscope",
      "input_per_mtok": 0.05,
      "output_per_mtok": 0.2
    },
    "dashscope/qwen-turbo-2025-04-28": {
      "provider": "dashscope",
      "input_per_mtok": 0.05,
      "output_per_mtok": 0.2
    },
    "dashscope/qwen-turbo-latest": {
      "provider": "dashscope",
      "input_per_mtok": 0.05,
      "output_per_mtok": 0.2
    },
    "dashscope/qwen3-next-80b-a3b-instruct": {
      "provider": "dashscope",
      "input_per_mtok": 0.15,
      "output_per_mtok": 1.2
    },
    "dashscope/qwen3-next-80b-a3b-thinking": {
      "provider": "dashscope",
      "input_per_mtok": 0.15,
      "output_per_mtok": 1.2
    },
    "dashscope/qwen3-vl-235b-a22b-instruct": {
      "provider": "dashscope",
      "input_per_mtok": 0.4,
      "output_per_mtok": 1.6
    },
    "dashscope/qwen3-vl-235b-a22b-thinking": {
      "provider": "dashscope",
      "input_per_mtok": 0.4,
      "output_per_mtok": 4.0
    },
    "deepcogito/cogito-v2.1-671b": {
      "provider": "openrouter",
      "free": false
    },
    "deepseek/deepseek-chat": {
      "provider": "openrouter",
      "input_per_mtok": 0.14,
      "output_per_mtok": 0.28,
      "free": false
    },
    "deepseek/deepseek-chat-v3-0324": {
      "provider": "openrouter",
      "input_per_mtok": 0.14,
      "output_per_mtok": 0.28,
      "free": false
    },
    "deepseek/deepseek-chat-v3.1": {
      "provider": "openrouter",
      "input_per_mtok": 0.2,
      "output_per_mtok": 0.8,
      "free": false
    },
    "deepseek/deepseek-r1": {
      "provider": "openrouter",
      "input_per_mtok": 0.55,
      "output_per_mtok": 2.19,
      "free": false
    },
    "deepseek/deepseek-r1-0528": {
      "provider": "openrouter",
      "input_per_mtok": 0.5,
      "output_per_mtok": 2.15,
      "free": false
    },
    "deepseek/deepseek-r1-distill-llama-70b": {
      "provider": "openrouter",
      "free": false
    },
    "deepseek/deepseek-r1-distill-qwen-32b": {
      "provider": "openrouter",
      "free": false
    },
    "deepseek/deepseek-v3.1-terminus": {
      "provider": "openrouter",
      "free": false
    },
    "deepseek/deepseek-v3.2": {
      "provider": "openrouter",
      "input_per_mtok": 0.28,
      "output_per_mtok": 0.4,
      "free": false
    },
    "deepseek/deepseek-v3.2-exp": {
      "provider": "openrouter",
      "input_per_mtok": 0.2,
      "output_per_mtok": 0.4,
      "free": false
    },
    "deepseek/deepseek-v3.2-speciale": {
      "provider": "openrouter",
      "free": false
    },
    "deepseek/deepseek-v4-flash": {
      "provider": "openrouter",
      "free": false
    },
    "deepseek/deepseek-v4-flash:free": {
      "provider": "openrouter",
      "free": true
    },
    "deepseek/deepseek-v4-pro": {
      "provider": "openrouter",
      "free": false
    },
    "essentialai/rnj-1-instruct": {
      "provider": "openrouter",
      "free": false
    },
    "gemini-2.5-flash": {
      "provider": "gemini",
      "input_per_mtok": 0.3,
      "output_per_mtok": 2.5,
      "cached_input_per_mtok": 0.03
    },
    "gemini-2.5-flash-lite": {
      "provider": "gemini",
      "input_per_mtok": 0.1,
      "output_per_mtok": 0.4,
      "cached_input_per_mtok": 0.01
    },
    "gemini-2.5-pro": {
      "provider": "gemini",
      "input_per_mtok": 1.25,
      "output_per_mtok": 10.0,
      "cached_input_per_mtok": 0.125
    },
    "gemini-3-flash-preview": {
      "provider": "gemini",
      "input_per_mtok": 0.5,
      "output_per_mtok": 3.0,
      "cached_input_per_mtok": 0.05
    },
    "gemini-3.1-flash-lite-preview": {
      "provider": "gemini",
      "input_per_mtok": 0.25,
      "output_per_mtok": 1.5,
      "cached_input_per_mtok": 0.025
    },
    "gemini-3.1-flash-live-preview": {
      "provider": "gemini",
      "input_per_mtok": 0.75,
      "output_per_mtok": 4.5
    },
    "gemini-3.1-pro-preview": {
      "provider": "gemini",
      "input_per_mtok": 2.0,
      "output_per_mtok": 12.0,
      "cached_input_per_mtok": 0.2
    },
    "gemini-3.1-pro-preview-customtools": {
      "provider": "gemini",
      "input_per_mtok": 2.0,
      "output_per_mtok": 12.0,
      "cached_input_per_mtok": 0.2
    },
    "gemini-flash-latest": {
      "provider": "gemini",
      "input_per_mtok": 0.3,
      "output_per_mtok": 2.5,
      "cached_input_per_mtok": 0.03
    },
    "gemini-flash-lite-latest": {
      "provider": "gemini",
      "input_per_mtok": 0.1,
      "output_per_mtok": 0.4,
      "cached_input_per_mtok": 0.01
    },
    "gemini-pro-latest": {
      "provider": "gemini",
      "input_per_mtok": 1.25,
      "output_per_mtok": 10.0,
      "cached_input_per_mtok": 0.125
    },
    "google/gemini-2.0-flash-001": {
      "provider": "openrouter",
      "input_per_mtok": 0.1,
      "output_per_mtok": 0.4,
      "free": false
    },
    "google/gemini-2.0-flash-lite-001": {
      "provider": "openrouter",
      "input_per_mtok": 0.075,
      "output_per_mtok": 0.3,
      "cached_input_per_mtok": 0.01875,
      "free": false
    },
    "google/gemini-2.5-flash": {
      "provider": "openrouter",
      "input_per_mtok": 0.3,
      "output_per_mtok": 2.5,
      "free": false
    },
    "google/gemini-2.5-flash-image": {
      "provider": "openrouter",
      "input_per_mtok": 0.3,
      "output_per_mtok": 2.5,
      "cached_input_per_mtok": 0.03,
      "free": false
    },
    "google/gemini-2.5-flash-lite": {
      "provider": "openrouter",
      "input_per_mtok": 0.1,
      "output_per_mtok": 0.4,
      "cached_input_per_mtok": 0.01,
      "free": false
    },
    "google/gemini-2.5-flash-lite-preview-09-2025": {
      "provider": "openrouter",
      "input_per_mtok": 0.1,
      "output_per_mtok": 0.4,
      "cached_input_per_mtok": 0.01,
      "free": false
    },
    "google/gemini-2.5-pro": {
      "provider": "openrouter",
      "input_per_mtok": 1.25,
      "output_per_mtok": 10.0,
      "free": false
    },
    "google/gemini-2.5-pro-preview": {
      "provider": "openrouter",
      "free": false
    },
    "google/gemini-2.5-pro-preview-05-06": {
      "provider": "openrouter",
      "free": false
    },
    "google/gemini-3-flash-preview": {
      "provider": "openrouter",
      "input_per_mtok": 0.5,
      "output_per_mtok": 3.0,
      "cached_input_per_mtok": 0.05,
      "free": false
    },
    "google/gemini-3-pro-image-preview": {
      "provider": "openrouter",
      "input_per_mtok": 2.0,
      "output_per_mtok": 12.0,
      "free": false
    },
    "google/gemini-3.1-flash-image-preview": {
      "provider": "openrouter",
      "input_per_mtok": 0.5,
      "output_per_mtok": 3.0,
      "free": false
    },
    "google/gemini-3.1-flash-lite": {
      "provider": "openrouter",
      "free": false
    },
    "google/gemini-3.1-flash-lite-preview": {
      "provider": "openrouter",
      "input_per_mtok": 0.25,
      "output_per_mtok": 1.5,
      "cached_input_per_mtok": 0.025,
      "free": false
    },
    "google/gemini-3.1-pro-preview": {
      "provider": "openrouter",
      "input_per_mtok": 2.0,
      "output_per_mtok": 12.0,
      "cached_input_per_mtok": 0.2,
      "free": false
    },
    "google/gemini-3.1-pro-preview-customtools": {
      "provider": "openrouter",
      "input_per_mtok": 2.0,
      "output_per_mtok": 12.0,
      "cached_input_per_mtok": 0.2,
      "free": false
    },
    "google/gemma-2-27b-it": {
      "provider": "openrouter",
      "free": false
    },
    "google/gemma-3-12b-it": {
      "provider": "openrouter",
      "free": false
    },
    "google/gemma-3-27b-it": {
      "provider": "openrouter",
      "free": false
    },
    "google/gemma-3-4b-it": {
      "provider": "openrouter",
      "free": false
    },
    "google/gemma-3n-e4b-it": {
      "provider": "openrouter",
      "free": false
    },
    "google/gemma-4-26b-a4b-it": {
      "provider": "openrouter",
      "free": false
    },
    "google/gemma-4-26b-a4b-it:free": {
      "provider": "openrouter",
      "free": true
    },
    "google/gemma-4-31b-it": {
      "provider": "openrouter",
      "free": false
    },
    "google/gemma-4-31b-it:free": {
      "provider": "openrouter",
      "free": true
    },
    "google/lyria-3-clip-preview": {
      "provider": "openrouter",
      "free": true
    },
    "google/lyria-3-pro-preview": {
      "provider": "openrouter",
      "free": true
    },
    "gpt-3.5-turbo": {
      "provider": "openai",
      "input_per_mtok": 0.5,
      "output_per_mtok": 1.5
    },
    "gpt-3.5-turbo-0125": {
      "provider": "openai",
      "input_per_mtok": 0.5,
      "output_per_mtok": 1.5
    },
    "gpt-3.5-turbo-1106": {
      "provider": "openai",
      "input_per_mtok": 1.0,
      "output_per_mtok": 2.0
    },
    "gpt-3.5-turbo-16k": {
      "provider": "openai",
      "input_per_mtok": 3.0,
      "output_per_mtok": 4.0
    },
    "gpt-3.5-turbo-instruct": {
      "provider": "openai",
      "input_per_mtok": 1.5,
      "output_per_mtok": 2.0
    },
    "gpt-3.5-turbo-instruct-0914": {
      "provider": "openai",
      "input_per_mtok": 1.5,
      "output_per_mtok": 2.0
    },
    "gpt-4": {
      "provider": "openai",
      "input_per_mtok": 30.0,
      "output_per_mtok": 60.0
    },
    "gpt-4-0613": {
      "provider": "openai",
      "input_per_mtok": 30.0,
      "output_per_mtok": 60.0
    },
    "gpt-4-turbo": {
      "provider": "openai",
      "input_per_mtok": 10.0,
      "output_per_mtok": 30.0
    },
    "gpt-4-turbo-2024-04-09": {
      "provider": "openai",
      "input_per_mtok": 10.0,
      "output_per_mtok": 30.0
    },
    "gpt-4.1": {
      "provider": "openai",
      "input_per_mtok": 2.0,
      "output_per_mtok": 8.0,
      "cached_input_per_mtok": 0.5
    },
    "gpt-4.1-2025-04-14": {
      "provider": "openai",
      "input_per_mtok": 2.0,
      "output_per_mtok": 8.0,
      "cached_input_per_mtok": 0.5
    },
    "gpt-4.1-mini": {
      "provider": "openai",
      "input_per_mtok": 0.4,
      "output_per_mtok": 1.6,
      "cached_input_per_mtok": 0.1
    },
    "gpt-4.1-mini-2025-04-14": {
      "provider": "openai",
      "input_per_mtok": 0.4,
      "output_per_mtok": 1.6,
      "cached_input_per_mtok": 0.1
    },
    "gpt-4.1-nano": {
      "provider": "openai",
      "input_per_mtok": 0.1,
      "output_per_mtok": 0.4,
      "cached_input_per_mtok": 0.025
    },
    "gpt-4.1-nano-2025-04-14": {
      "provider": "openai",
      "input_per_mtok": 0.1,
      "output_per_mtok": 0.4,
      "cached_input_per_mtok": 0.025
    },
    "gpt-4o": {
      "provider": "openai",
      "input_per_mtok": 2.5,
      "output_per_mtok": 10.0,
      "cached_input_per_mtok": 1.25
    },
    "gpt-4o-2024-05-13": {
      "provider": "openai",
      "input_per_mtok": 5.0,
      "output_per_mtok": 15.0
    },
    "gpt-4o-2024-08-06": {
      "provider": "openai",
      "input_per_mtok": 2.5,
      "output_per_mtok": 10.0,
      "cached_input_per_mtok": 1.25
    },
    "gpt-4o-2024-11-20": {
      "provider": "openai",
      "input_per_mtok": 2.5,
      "output_per_mtok": 10.0,
      "cached_input_per_mtok": 1.25
    },
    "gpt-4o-mini": {
      "provider": "openai",
      "input_per_mtok": 0.15,
      "output_per_mtok": 0.6,
      "cached_input_per_mtok": 0.075
    },
    "gpt-4o-mini-2024-07-18": {
      "provider": "openai",
      "input_per_mtok": 0.15,
      "output_per_mtok": 0.6,
      "cached_input_per_mtok": 0.075
    },
    "gpt-5": {
      "provider": "openai",
      "input_per_mtok": 1.25,
      "output_per_mtok": 10.0,
      "cached_input_per_mtok": 0.125
    },
    "gpt-5-2025-08-07": {
      "provider": "openai",
      "input_per_mtok": 1.25,
      "output_per_mtok": 10.0,
      "cached_input_per_mtok": 0.125
    },
    "gpt-5-chat-latest": {
      "provider": "openai",
      "input_per_mtok": 1.25,
      "output_per_mtok": 10.0,
      "cached_input_per_mtok": 0.125
    },
    "gpt-5-codex": {
      "provider": "openai",
      "input_per_mtok": 1.25,
      "output_per_mtok": 10.0,
      "cached_input_per_mtok": 0.125
    },
    "gpt-5-mini": {
      "provider": "openai",
      "input_per_mtok": 0.25,
      "output_per_mtok": 2.0,
      "cached_input_per_mtok": 0.025
    },
    "gpt-5-mini-2025-08-07": {
      "provider": "openai",
      "input_per_mtok": 0.25,
      "output_per_mtok": 2.0,
      "cached_input_per_mtok": 0.025
    },
    "gpt-5-nano": {
      "provider": "openai",
      "input_per_mtok": 0.05,
      "output_per_mtok": 0.4,
      "cached_input_per_mtok": 0.005
    },
    "gpt-5-nano-2025-08-07": {
      "provider": "openai",
      "input_per_mtok": 0.05,
      "output_per_mtok": 0.4,
      "cached_input_per_mtok": 0.005
    },
    "gpt-5-pro": {
      "provider": "openai",
      "input_per_mtok": 15.0,
      "output_per_mtok": 120.0
    },
    "gpt-5-pro-2025-10-06": {
      "provider": "openai",
      "input_per_mtok": 15.0,
      "output_per_mtok": 120.0
    },
    "gpt-5-search-api": {
      "provider": "openai",
      "input_per_mtok": 1.25,
      "output_per_mtok": 10.0,
      "cached_input_per_mtok": 0.125
    },
    "gpt-5-search-api-2025-10-14": {
      "provider": "openai",
      "input_per_mtok": 1.25,
      "output_per_mtok": 10.0,
      "cached_input_per_mtok": 0.125
    },
    "gpt-5.1": {
      "provider": "openai",
      "input_per_mtok": 1.25,
      "output_per_mtok": 10.0,
      "cached_input_per_mtok": 0.125
    },
    "gpt-5.1-2025-11-13": {
      "provider": "openai",
      "input_per_mtok": 1.25,
      "output_per_mtok": 10.0,
      "cached_input_per_mtok": 0.125
    },
    "gpt-5.1-chat-latest": {
      "provider": "openai",
      "input_per_mtok": 1.25,
      "output_per_mtok": 10.0,
      "cached_input_per_mtok": 0.125
    },
    "gpt-5.1-codex": {
      "provider": "openai",
      "input_per_mtok": 1.25,
      "output_per_mtok": 10.0,
      "cached_input_per_mtok": 0.125
    },
    "gpt-5.1-codex-max": {
      "provider": "openai",
      "input_per_mtok": 1.25,
      "output_per_mtok": 10.0,
      "cached_input_per_mtok": 0.125
    },
    "gpt-5.1-codex-mini": {
      "provider": "openai",
      "input_per_mtok": 0.25,
      "output_per_mtok": 2.0,
      "cached_input_per_mtok": 0.025
    },
    "gpt-5.2": {
      "provider": "openai",
      "input_per_mtok": 1.75,
      "output_per_mtok": 14.0,
      "cached_input_per_mtok": 0.175
    },
    "gpt-5.2-2025-12-11": {
      "provider": "openai",
      "input_per_mtok": 1.75,
      "output_per_mtok": 14.0,
      "cached_input_per_mtok": 0.175
    },
    "gpt-5.2-chat-latest": {
      "provider": "openai",
      "input_per_mtok": 1.75,
      "output_per_mtok": 14.0,
      "cached_input_per_mtok": 0.175
    },
    "gpt-5.2-codex": {
      "provider": "openai",
      "input_per_mtok": 1.75,
      "output_per_mtok": 14.0,
      "cached_input_per_mtok": 0.175
    },
    "gpt-5.2-pro": {
      "provider": "openai",
      "input_per_mtok": 21.0,
      "output_per_mtok": 168.0
    },
    "gpt-5.2-pro-2025-12-11": {
      "provider": "openai",
      "input_per_mtok": 21.0,
      "output_per_mtok": 168.0
    },
    "gpt-5.3-chat-latest": {
      "provider": "openai",
      "input_per_mtok": 1.75,
      "output_per_mtok": 14.0,
      "cached_input_per_mtok": 0.175
    },
    "gpt-5.3-codex": {
      "provider": "openai",
      "input_per_mtok": 1.75,
      "output_per_mtok": 14.0,
      "cached_input_per_mtok": 0.175
    },
    "gpt-5.4": {
      "provider": "openai",
      "input_per_mtok": 2.5,
      "output_per_mtok": 15.0,
      "cached_input_per_mtok": 0.25
    },
    "gpt-5.4-2026-03-05": {
      "provider": "openai",
      "input_per_mtok": 2.5,
      "output_per_mtok": 15.0,
      "cached_input_per_mtok": 0.25
    },
    "gpt-5.4-mini": {
      "provider": "openai",
      "input_per_mtok": 0.75,
      "output_per_mtok": 4.5,
      "cached_input_per_mtok": 0.075
    },
    "gpt-5.4-mini-2026-03-17": {
      "provider": "openai",
      "input_per_mtok": 0.75,
      "output_per_mtok": 4.5,
      "cached_input_per_mtok": 0.075
    },
    "gpt-5.4-nano": {
      "provider": "openai",
      "input_per_mtok": 0.2,
      "output_per_mtok": 1.25,
      "cached_input_per_mtok": 0.02
    },
    "gpt-5.4-nano-2026-03-17": {
      "provider": "openai",
      "input_per_mtok": 0.2,
      "output_per_mtok": 1.25,
      "cached_input_per_mtok": 0.02
    },
    "gpt-5.4-pro": {
      "provider": "openai",
      "input_per_mtok": 30.0,
      "output_per_mtok": 180.0,
      "cached_input_per_mtok": 3.0
    },
    "gpt-5.4-pro-2026-03-05": {
      "provider": "openai",
      "input_per_mtok": 30.0,
      "output_per_mtok": 180.0,
      "cached_input_per_mtok": 3.0
    },
    "gpt-5.5": {
      "provider": "openai",
      "input_per_mtok": 5.0,
      "output_per_mtok": 30.0,
      "cached_input_per_mtok": 0.5
    },
    "gpt-5.5-2026-04-23": {
      "provider": "openai",
      "input_per_mtok": 5.0,
      "output_per_mtok": 30.0,
      "cached_input_per_mtok": 0.5
    },
    "gpt-5.5-pro": {
      "provider": "openai",
      "input_per_mtok": 30.0,
      "output_per_mtok": 180.0,
      "cached_input_per_mtok": 3.0
    },
    "gpt-5.5-pro-2026-04-23": {
      "provider": "openai",
      "input_per_mtok": 30.0,
      "output_per_mtok": 180.0,
      "cached_input_per_mtok": 3.0
    },
    "gryphe/mythomax-l2-13b": {
      "provider": "openrouter",
      "input_per_mtok": 1.875,
      "output_per_mtok": 1.875,
      "free": false
    },
    "ibm-granite/granite-4.0-h-micro": {
      "provider": "openrouter",
      "free": false
    },
    "ibm-granite/granite-4.1-8b": {
      "provider": "openrouter",
      "free": false
    },
    "inception/mercury-2": {
      "provider": "openrouter",
      "free": false
    },
    "inclusionai/ling-2.6-1t": {
      "provider": "openrouter",
      "free": false
    },
    "inclusionai/ling-2.6-flash": {
      "provider": "openrouter",
      "free": false
    },
    "inclusionai/ring-2.6-1t:free": {
      "provider": "openrouter",
      "free": true
    },
    "inflection/inflection-3-pi": {
      "provider": "openrouter",
      "free": false
    },
    "inflection/inflection-3-productivity": {
      "provider": "openrouter",
      "free": false
    },
    "kwaipilot/kat-coder-pro-v2": {
      "provider": "openrouter",
      "free": false
    },
    "liquid/lfm-2-24b-a2b": {
      "provider": "openrouter",
      "free": false
    },
    "liquid/lfm-2.5-1.2b-instruct:free": {
      "provider": "openrouter",
      "free": true
    },
    "liquid/lfm-2.5-1.2b-thinking:free": {
      "provider": "openrouter",
      "free": true
    },
    "mancer/weaver": {
      "provider": "openrouter",
      "input_per_mtok": 5.625,
      "output_per_mtok": 5.625,
      "free": false
    },
    "meta-llama/llama-3-70b-instruct": {
      "provider": "openrouter",
      "input_per_mtok": 0.59,
      "output_per_mtok": 0.79,
      "free": false
    },
    "meta-llama/llama-3-8b-instruct": {
      "provider": "openrouter",
      "free": false
    },
    "meta-llama/llama-3.1-70b-instruct": {
      "provider": "openrouter",
      "free": false
    },
    "meta-llama/llama-3.1-8b-instruct": {
      "provider": "openrouter",
      "free": false
    },
    "meta-llama/llama-3.2-11b-vision-instruct": {
      "provider": "openrouter",
      "free": false
    },
    "meta-llama/llama-3.2-1b-instruct": {
      "provider": "openrouter",
      "free": false
    },
    "meta-llama/llama-3.2-3b-instruct": {
      "provider": "openrouter",
      "free": false
    },
    "meta-llama/llama-3.2-3b-instruct:free": {
      "provider": "openrouter",
      "free": true
    },
    "meta-llama/llama-3.3-70b-instruct": {
      "provider": "openrouter",
      "free": false
    },
    "meta-llama/llama-3.3-70b-instruct:free": {
      "provider": "openrouter",
      "free": true
    },
    "meta-llama/llama-4-maverick": {
      "provider": "openrouter",
      "free": false
    },
    "meta-llama/llama-4-scout": {
      "provider": "openrouter",
      "free": false
    },
    "meta-llama/llama-guard-3-8b": {
      "provider": "openrouter",
      "free": false
    },
    "meta-llama/llama-guard-4-12b": {
      "provider": "openrouter",
      "free": false
    },
    "microsoft/phi-4": {
      "provider": "openrouter",
      "free": false
    },
    "microsoft/phi-4-mini-instruct": {
      "provider": "openrouter",
      "free": false
    },
    "microsoft/wizardlm-2-8x22b": {
      "provider": "openrouter",
      "free": false
    },
    "minimax/MiniMax-M2": {
      "provider": "minimax",
      "input_per_mtok": 0.3,
      "output_per_mtok": 1.2,
      "cached_input_per_mtok": 0.03,
      "cache_creation_per_mtok": 0.375
    },
    "minimax/MiniMax-M2.1": {
      "provider": "minimax",
      "input_per_mtok": 0.3,
      "output_per_mtok": 1.2,
      "cached_input_per_mtok": 0.03,
      "cache_creation_per_mtok": 0.375
    },
    "minimax/MiniMax-M2.5": {
      "provider": "minimax",
      "input_per_mtok": 0.3,
      "output_per_mtok": 1.2,
      "cached_input_per_mtok": 0.03,
      "cache_creation_per_mtok": 0.375
    },
    "minimax/minimax-01": {
      "provider": "openrouter",
      "free": false
    },
    "minimax/minimax-m1": {
      "provider": "openrouter",
      "free": false
    },
    "minimax/minimax-m2": {
      "provider": "openrouter",
      "input_per_mtok": 0.255,
      "output_per_mtok": 1.02,
      "free": false
    },
    "minimax/minimax-m2-her": {
      "provider": "openrouter",
      "free": false
    },
    "minimax/minimax-m2.1": {
      "provider": "openrouter",
      "input_per_mtok": 0.27,
      "output_per_mtok": 1.2,
      "cached_input_per_mtok": 0.0,
      "cache_creation_per_mtok": 0.0,
      "free": false
    },
    "minimax/minimax-m2.5": {
      "provider": "openrouter",
      "input_per_mtok": 0.3,
      "output_per_mtok": 1.1,
      "cached_input_per_mtok": 0.15,
      "free": false
    },
    "minimax/minimax-m2.5:free": {
      "provider": "openrouter",
      "free": true
    },
    "minimax/minimax-m2.7": {
      "provider": "openrouter",
      "free": false
    },
    "mistralai/codestral-2508": {
      "provider": "openrouter",
      "free": false
    },
    "mistralai/devstral-2512": {
      "provider": "openrouter",
      "input_per_mtok": 0.15,
      "output_per_mtok": 0.6,
      "free": false
    },
    "mistralai/devstral-medium": {
      "provider": "openrouter",
      "free": false
    },
    "mistralai/devstral-small": {
      "provider": "openrouter",
      "free": false
    },
    "mistralai/ministral-14b-2512": {
      "provider": "openrouter",
      "input_per_mtok": 0.2,
      "output_per_mtok": 0.2,
      "free": false
    },
    "mistralai/ministral-3b-2512": {
      "provider": "openrouter",
      "input_per_mtok": 0.1,
      "output_per_mtok": 0.1,
      "free": false
    },
    "mistralai/ministral-8b-2512": {
      "provider": "openrouter",
      "input_per_mtok": 0.15,
      "output_per_mtok": 0.15,
      "free": false
    },
    "mistralai/mistral-7b-instruct-v0.1": {
      "provider": "openrouter",
      "free": false
    },
    "mistralai/mistral-large": {
      "provider": "openrouter",
      "input_per_mtok": 8.0,
      "output_per_mtok": 24.0,
      "free": false
    },
    "mistralai/mistral-large-2407": {
      "provider": "openrouter",
      "free": false
    },
    "mistralai/mistral-large-2411": {
      "provider": "openrouter",
      "free": false
    },
    "mistralai/mistral-large-2512": {
      "provider": "openrouter",
      "input_per_mtok": 0.5,
      "output_per_mtok": 1.5,
      "free": false
    },
    "mistralai/mistral-medium-3": {
      "provider": "openrouter",
      "free": false
    },
    "mistralai/mistral-medium-3-5": {
      "provider": "openrouter",
      "free": false
    },
    "mistralai/mistral-medium-3.1": {
      "provider": "openrouter",
      "free": false
    },
    "mistralai/mistral-nemo": {
      "provider": "openrouter",
      "free": false
    },
    "mistralai/mistral-saba": {
      "provider": "openrouter",
      "free": false
    },
    "mistralai/mistral-small-24b-instruct-2501": {
      "provider": "openrouter",
      "free": false
    },
    "mistralai/mistral-small-2603": {
      "provider": "openrouter",
      "free": false
    },
    "mistralai/mistral-small-3.1-24b-instruct": {
      "provider": "openrouter",
      "input_per_mtok": 0.1,
      "output_per_mtok": 0.3,
      "free": false
    },
    "mistralai/mistral-small-3.2-24b-instruct": {
      "provider": "openrouter",
      "input_per_mtok": 0.1,
      "output_per_mtok": 0.3,
      "free": false
    },
    "mistralai/mixtral-8x22b-instruct": {
      "provider": "openrouter",
      "input_per_mtok": 0.65,
      "output_per_mtok": 0.65,
      "free": false
    },
    "mistralai/pixtral-large-2411": {
      "provider": "openrouter",
      "free": false
    },
    "mistralai/voxtral-small-24b-2507": {
      "provider": "openrouter",
      "free": false
    },
    "moonshotai/kimi-k2": {
      "provider": "openrouter",
      "free": false
    },
    "moonshotai/kimi-k2-0905": {
      "provider": "openrouter",
      "free": false
    },
    "moonshotai/kimi-k2-thinking": {
      "provider": "openrouter",
      "free": false
    },
    "moonshotai/kimi-k2.5": {
      "provider": "openrouter",
      "input_per_mtok": 0.6,
      "output_per_mtok": 3.0,
      "cached_input_per_mtok": 0.1,
      "free": false
    },
    "moonshotai/kimi-k2.6": {
      "provider": "openrouter",
      "free": false
    },
    "morph/morph-v3-fast": {
      "provider": "openrouter",
      "input_per_mtok": 0.8,
      "output_per_mtok": 1.2,
      "free": false
    },
    "morph/morph-v3-large": {
      "provider": "openrouter",
      "input_per_mtok": 0.9,
      "output_per_mtok": 1.9,
      "free": false
    },
    "nex-agi/deepseek-v3.1-nex-n1": {
      "provider": "openrouter",
      "free": false
    },
    "nousresearch/hermes-2-pro-llama-3-8b": {
      "provider": "openrouter",
      "free": false
    },
    "nousresearch/hermes-3-llama-3.1-405b": {
      "provider": "openrouter",
      "free": false
    },
    "nousresearch/hermes-3-llama-3.1-405b:free": {
      "provider": "openrouter",
      "free": true
    },
    "nousresearch/hermes-3-llama-3.1-70b": {
      "provider": "openrouter",
      "free": false
    },
    "nousresearch/hermes-4-405b": {
      "provider": "openrouter",
      "free": false
    },
    "nousresearch/hermes-4-70b": {
      "provider": "openrouter",
      "free": false
    },
    "nvidia/llama-3.3-nemotron-super-49b-v1.5": {
      "provider": "openrouter",
      "free": false
    },
    "nvidia/nemotron-3-nano-30b-a3b": {
      "provider": "openrouter",
      "free": false
    },
    "nvidia/nemotron-3-nano-30b-a3b:free": {
      "provider": "openrouter",
      "free": true
    },
    "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free": {
      "provider": "openrouter",
      "free": true
    },
    "nvidia/nemotron-3-super-120b-a12b": {
      "provider": "openrouter",
      "free": false
    },
    "nvidia/nemotron-3-super-120b-a12b:free": {
      "provider": "openrouter",
      "free": true
    },
    "nvidia/nemotron-nano-12b-v2-vl:free": {
      "provider": "openrouter",
      "free": true
    },
    "nvidia/nemotron-nano-9b-v2": {
      "provider": "openrouter",
      "free": false
    },
    "nvidia/nemotron-nano-9b-v2:free": {
      "provider": "openrouter",
      "free": true
    },
    "o1": {
      "provider": "openai",
      "input_per_mtok": 15.0,
      "output_per_mtok": 60.0,
      "cached_input_per_mtok": 7.5
    },
    "o1-2024-12-17": {
      "provider": "openai",
      "input_per_mtok": 15.0,
      "output_per_mtok": 60.0,
      "cached_input_per_mtok": 7.5
    },
    "o1-pro": {
      "provider": "openai",
      "input_per_mtok": 150.0,
      "output_per_mtok": 600.0
    },
    "o1-pro-2025-03-19": {
      "provider": "openai",
      "input_per_mtok": 150.0,
      "output_per_mtok": 600.0
    },
    "o3": {
      "provider": "openai",
      "input_per_mtok": 2.0,
      "output_per_mtok": 8.0,
      "cached_input_per_mtok": 0.5
    },
    "o3-2025-04-16": {
      "provider": "openai",
      "input_per_mtok": 2.0,
      "output_per_mtok": 8.0,
      "cached_input_per_mtok": 0.5
    },
    "o3-deep-research": {
      "provider": "openai",
      "input_per_mtok": 10.0,
      "output_per_mtok": 40.0,
      "cached_input_per_mtok": 2.5
    },
    "o3-deep-research-2025-06-26": {
      "provider": "openai",
      "input_per_mtok": 10.0,
      "output_per_mtok": 40.0,
      "cached_input_per_mtok": 2.5
    },
    "o3-mini": {
      "provider": "openai",
      "input_per_mtok": 1.1,
      "output_per_mtok": 4.4,
      "cached_input_per_mtok": 0.55
    },
    "o3-mini-2025-01-31": {
      "provider": "openai",
      "input_per_mtok": 1.1,
      "output_per_mtok": 4.4,
      "cached_input_per_mtok": 0.55
    },
    "o3-pro": {
      "provider": "openai",
      "input_per_mtok": 20.0,
      "output_per_mtok": 80.0
    },
    "o3-pro-2025-06-10": {
      "provider": "openai",
      "input_per_mtok": 20.0,
      "output_per_mtok": 80.0
    },
    "o4-mini": {
      "provider": "openai",
      "input_per_mtok": 1.1,
      "output_per_mtok": 4.4,
      "cached_input_per_mtok": 0.275
    },
    "o4-mini-2025-04-16": {
      "provider": "openai",
      "input_per_mtok": 1.1,
      "output_per_mtok": 4.4,
      "cached_input_per_mtok": 0.275
    },
    "o4-mini-deep-research": {
      "provider": "openai",
      "input_per_mtok": 2.0,
      "output_per_mtok": 8.0,
      "cached_input_per_mtok": 0.5
    },
    "o4-mini-deep-research-2025-06-26": {
      "provider": "openai",
      "input_per_mtok": 2.0,
      "output_per_mtok": 8.0,
      "cached_input_per_mtok": 0.5
    },
    "ollama-cloud/gemini-3-flash-preview": {
      "provider": "ollama-cloud",
      "input_per_mtok": 0.5,
      "output_per_mtok": 3.0,
      "cached_input_per_mtok": 0.05
    },
    "openai/gpt-3.5-turbo": {
      "provider": "openrouter",
      "input_per_mtok": 1.5,
      "output_per_mtok": 2.0,
      "free": false
    },
    "openai/gpt-3.5-turbo-0613": {
      "provider": "openrouter",
      "free": false
    },
    "openai/gpt-3.5-turbo-16k": {
      "provider": "openrouter",
      "input_per_mtok": 3.0,
      "output_per_mtok": 4.0,
      "free": false
    },
    "openai/gpt-3.5-turbo-instruct": {
      "provider": "openrouter",
      "input_per_mtok": 1.5,
      "output_per_mtok": 2.0,
      "free": false
    },
    "openai/gpt-4": {
      "provider": "openrouter",
      "input_per_mtok": 30.0,
      "output_per_mtok": 60.0,
      "free": false
    },
    "openai/gpt-4-0314": {
      "provider": "openrouter",
      "input_per_mtok": 30.0,
      "output_per_mtok": 60.0,
      "free": false
    },
    "openai/gpt-4-1106-preview": {
      "provider": "openrouter",
      "input_per_mtok": 10.0,
      "output_per_mtok": 30.0,
      "free": false
    },
    "openai/gpt-4-turbo": {
      "provider": "openrouter",
      "input_per_mtok": 10.0,
      "output_per_mtok": 30.0,
      "free": false
    },
    "openai/gpt-4-turbo-preview": {
      "provider": "openrouter",
      "input_per_mtok": 10.0,
      "output_per_mtok": 30.0,
      "free": false
    },
    "openai/gpt-4.1": {
      "provider": "openrouter",
      "input_per_mtok": 2.0,
      "output_per_mtok": 8.0,
      "cached_input_per_mtok": 0.5,
      "free": false
    },
    "openai/gpt-4.1-mini": {
      "provider": "openrouter",
      "input_per_mtok": 0.4,
      "output_per_mtok": 1.6,
      "cached_input_per_mtok": 0.1,
      "free": false
    },
    "openai/gpt-4.1-nano": {
      "provider": "openrouter",
      "input_per_mtok": 0.1,
      "output_per_mtok": 0.4,
      "cached_input_per_mtok": 0.025,
      "free": false
    },
    "openai/gpt-4o": {
      "provider": "openrouter",
      "input_per_mtok": 2.5,
      "output_per_mtok": 10.0,
      "free": false
    },
    "openai/gpt-4o-2024-05-13": {
      "provider": "openrouter",
      "input_per_mtok": 5.0,
      "output_per_mtok": 15.0,
      "free": false
    },
    "openai/gpt-4o-2024-08-06": {
      "provider": "openrouter",
      "input_per_mtok": 2.5,
      "output_per_mtok": 10.0,
      "cached_input_per_mtok": 1.25,
      "free": false
    },
    "openai/gpt-4o-2024-11-20": {
      "provider": "openrouter",
      "input_per_mtok": 2.5,
      "output_per_mtok": 10.0,
      "cached_input_per_mtok": 1.25,
      "free": false
    },
    "openai/gpt-4o-audio-preview": {
      "provider": "openrouter",
      "input_per_mtok": 2.5,
      "output_per_mtok": 10.0,
      "free": false
    },
    "openai/gpt-4o-mini": {
      "provider": "openrouter",
      "input_per_mtok": 0.15,
      "output_per_mtok": 0.6,
      "cached_input_per_mtok": 0.075,
      "free": false
    },
    "openai/gpt-4o-mini-2024-07-18": {
      "provider": "openrouter",
      "input_per_mtok": 0.15,
      "output_per_mtok": 0.6,
      "cached_input_per_mtok": 0.075,
      "free": false
    },
    "openai/gpt-4o-mini-search-preview": {
      "provider": "openrouter",
      "input_per_mtok": 0.15,
      "output_per_mtok": 0.6,
      "cached_input_per_mtok": 0.075,
      "free": false
    },
    "openai/gpt-4o-search-preview": {
      "provider": "openrouter",
      "input_per_mtok": 2.5,
      "output_per_mtok": 10.0,
      "cached_input_per_mtok": 1.25,
      "free": false
    },
    "openai/gpt-5": {
      "provider": "openrouter",
      "input_per_mtok": 1.25,
      "output_per_mtok": 10.0,
      "cached_input_per_mtok": 0.125,
      "free": false
    },
    "openai/gpt-5-chat": {
      "provider": "openrouter",
      "input_per_mtok": 1.25,
      "output_per_mtok": 10.0,
      "cached_input_per_mtok": 0.125,
      "free": false
    },
    "openai/gpt-5-codex": {
      "provider": "openrouter",
      "input_per_mtok": 1.25,
      "output_per_mtok": 10.0,
      "cached_input_per_mtok": 0.125,
      "free": false
    },
    "openai/gpt-5-image": {
      "provider": "openrouter",
      "free": false
    },
    "openai/gpt-5-image-mini": {
      "provider": "openrouter",
      "free": false
    },
    "openai/gpt-5-mini": {
      "provider": "openrouter",
      "input_per_mtok": 0.25,
      "output_per_mtok": 2.0,
      "cached_input_per_mtok": 0.025,
      "free": false
    },
    "openai/gpt-5-nano": {
      "provider": "openrouter",
      "input_per_mtok": 0.05,
      "output_per_mtok": 0.4,
      "cached_input_per_mtok": 0.005,
      "free": false
    },
    "openai/gpt-5-pro": {
      "provider": "openrouter",
      "input_per_mtok": 15.0,
      "output_per_mtok": 120.0,
      "free": false
    },
    "openai/gpt-5.1": {
      "provider": "openrouter",
      "input_per_mtok": 1.25,
      "output_per_mtok": 10.0,
      "cached_input_per_mtok": 0.125,
      "free": false
    },
    "openai/gpt-5.1-chat": {
      "provider": "openrouter",
      "free": false
    },
    "openai/gpt-5.1-codex": {
      "provider": "openrouter",
      "input_per_mtok": 1.25,
      "output_per_mtok": 10.0,
      "cached_input_per_mtok": 0.125,
      "free": false
    },
    "openai/gpt-5.1-codex-max": {
      "provider": "openrouter",
      "input_per_mtok": 1.25,
      "output_per_mtok": 10.0,
      "cached_input_per_mtok": 0.125,
      "free": false
    },
    "openai/gpt-5.1-codex-mini": {
      "provider": "openrouter",
      "input_per_mtok": 0.25,
      "output_per_mtok": 2.0,
      "cached_input_per_mtok": 0.025,
      "free": false
    },
    "openai/gpt-5.2": {
      "provider": "openrouter",
      "input_per_mtok": 1.75,
      "output_per_mtok": 14.0,
      "cached_input_per_mtok": 0.175,
      "free": false
    },
    "openai/gpt-5.2-chat": {
      "provider": "openrouter",
      "input_per_mtok": 1.75,
      "output_per_mtok": 14.0,
      "cached_input_per_mtok": 0.175,
      "free": false
    },
    "openai/gpt-5.2-codex": {
      "provider": "openrouter",
      "input_per_mtok": 1.75,
      "output_per_mtok": 14.0,
      "cached_input_per_mtok": 0.175,
      "free": false
    },
    "openai/gpt-5.2-pro": {
      "provider": "openrouter",
      "input_per_mtok": 21.0,
      "output_per_mtok": 168.0,
      "free": false
    },
    "openai/gpt-5.3-chat": {
      "provider": "openrouter",
      "free": false
    },
    "openai/gpt-5.3-codex": {
      "provider": "openrouter",
      "input_per_mtok": 1.75,
      "output_per_mtok": 14.0,
      "cached_input_per_mtok": 0.175,
      "free": false
    },
    "openai/gpt-5.4": {
      "provider": "openrouter",
      "input_per_mtok": 2.5,
      "output_per_mtok": 15.0,
      "cached_input_per_mtok": 0.25,
      "free": false
    },
    "openai/gpt-5.4-image-2": {
      "provider": "openrouter",
      "free": false
    },
    "openai/gpt-5.4-mini": {
      "provider": "openrouter",
      "input_per_mtok": 0.75,
      "output_per_mtok": 4.5,
      "cached_input_per_mtok": 0.075,
      "free": false
    },
    "openai/gpt-5.4-nano": {
      "provider": "openrouter",
      "input_per_mtok": 0.2,
      "output_per_mtok": 1.25,
      "cached_input_per_mtok": 0.02,
      "free": false
    },
    "openai/gpt-5.4-pro": {
      "provider": "openrouter",
      "input_per_mtok": 30.0,
      "output_per_mtok": 180.0,
      "cached_input_per_mtok": 3.0,
      "free": false
    },
    "openai/gpt-5.5": {
      "provider": "openrouter",
      "input_per_mtok": 5.0,
      "output_per_mtok": 30.0,
      "cached_input_per_mtok": 0.5,
      "free": false
    },
    "openai/gpt-5.5-pro": {
      "provider": "openrouter",
      "input_per_mtok": 30.0,
      "output_per_mtok": 180.0,
      "cached_input_per_mtok": 3.0,
      "free": false
    },
    "openai/gpt-audio": {
      "provider": "openrouter",
      "input_per_mtok": 2.5,
      "output_per_mtok": 10.0,
      "free": false
    },
    "openai/gpt-audio-mini": {
      "provider": "openrouter",
      "input_per_mtok": 0.6,
      "output_per_mtok": 2.4,
      "free": false
    },
    "openai/gpt-chat-latest": {
      "provider": "openrouter",
      "free": false
    },
    "openai/gpt-oss-120b": {
      "provider": "openrouter",
      "input_per_mtok": 0.18,
      "output_per_mtok": 0.8,
      "free": false
    },
    "openai/gpt-oss-120b:free": {
      "provider": "openrouter",
      "free": true
    },
    "openai/gpt-oss-20b": {
      "provider": "openrouter",
      "input_per_mtok": 0.02,
      "output_per_mtok": 0.1,
      "free": false
    },
    "openai/gpt-oss-20b:free": {
      "provider": "openrouter",
      "free": true
    },
    "openai/gpt-oss-safeguard-20b": {
      "provider": "openrouter",
      "free": false
    },
    "openai/o1": {
      "provider": "openrouter",
      "input_per_mtok": 15.0,
      "output_per_mtok": 60.0,
      "cached_input_per_mtok": 7.5,
      "free": false
    },
    "openai/o1-pro": {
      "provider": "openrouter",
      "input_per_mtok": 150.0,
      "output_per_mtok": 600.0,
      "free": false
    },
    "openai/o3": {
      "provider": "openrouter",
      "input_per_mtok": 2.0,
      "output_per_mtok": 8.0,
      "cached_input_per_mtok": 0.5,
      "free": false
    },
    "openai/o3-deep-research": {
      "provider": "openrouter",
      "input_per_mtok": 10.0,
      "output_per_mtok": 40.0,
      "cached_input_per_mtok": 2.5,
      "free": false
    },
    "openai/o3-mini": {
      "provider": "openrouter",
      "input_per_mtok": 1.1,
      "output_per_mtok": 4.4,
      "free": false
    },
    "openai/o3-mini-high": {
      "provider": "openrouter",
      "input_per_mtok": 1.1,
      "output_per_mtok": 4.4,
      "free": false
    },
    "openai/o3-pro": {
      "provider": "openrouter",
      "input_per_mtok": 20.0,
      "output_per_mtok": 80.0,
      "free": false
    },
    "openai/o4-mini": {
      "provider": "openrouter",
      "input_per_mtok": 1.1,
      "output_per_mtok": 4.4,
      "cached_input_per_mtok": 0.275,
      "free": false
    },
    "openai/o4-mini-deep-research": {
      "provider": "openrouter",
      "input_per_mtok": 2.0,
      "output_per_mtok": 8.0,
      "cached_input_per_mtok": 0.5,
      "free": false
    },
    "openai/o4-mini-high": {
      "provider": "openrouter",
      "free": false
    },
    "openrouter/auto": {
      "provider": "openrouter",
      "input_per_mtok": 0,
      "output_per_mtok": 0,
      "free": false
    },
    "openrouter/bodybuilder": {
      "provider": "openrouter",
      "input_per_mtok": 0,
      "output_per_mtok": 0,
      "free": false
    },
    "openrouter/free": {
      "provider": "openrouter",
      "input_per_mtok": 0,
      "output_per_mtok": 0,
      "free": true
    },
    "openrouter/owl-alpha": {
      "provider": "openrouter",
      "free": true
    },
    "openrouter/pareto-code": {
      "provider": "openrouter",
      "free": false
    },
    "perceptron/perceptron-mk1": {
      "provider": "openrouter",
      "free": false
    },
    "perplexity/sonar": {
      "provider": "openrouter",
      "input_per_mtok": 1.0,
      "output_per_mtok": 1.0,
      "free": false
    },
    "perplexity/sonar-deep-research": {
      "provider": "openrouter",
      "input_per_mtok": 2.0,
      "output_per_mtok": 8.0,
      "free": false
    },
    "perplexity/sonar-pro": {
      "provider": "openrouter",
      "input_per_mtok": 3.0,
      "output_per_mtok": 15.0,
      "free": false
    },
    "perplexity/sonar-pro-search": {
      "provider": "openrouter",
      "free": false
    },
    "perplexity/sonar-reasoning-pro": {
      "provider": "openrouter",
      "input_per_mtok": 2.0,
      "output_per_mtok": 8.0,
      "free": false
    },
    "poolside/laguna-m.1:free": {
      "provider": "openrouter",
      "free": true
    },
    "poolside/laguna-xs.2:free": {
      "provider": "openrouter",
      "free": true
    },
    "prime-intellect/intellect-3": {
      "provider": "openrouter",
      "free": false
    },
    "qwen-max": {
      "provider": "dashscope",
      "input_per_mtok": 1.6,
      "output_per_mtok": 6.4
    },
    "qwen-plus": {
      "provider": "dashscope",
      "input_per_mtok": 0.4,
      "output_per_mtok": 1.2
    },
    "qwen-plus-2025-01-25": {
      "provider": "dashscope",
      "input_per_mtok": 0.4,
      "output_per_mtok": 1.2
    },
    "qwen-plus-2025-04-28": {
      "provider": "dashscope",
      "input_per_mtok": 0.4,
      "output_per_mtok": 1.2
    },
    "qwen-plus-2025-07-14": {
      "provider": "dashscope",
      "input_per_mtok": 0.4,
      "output_per_mtok": 1.2
    },
    "qwen-turbo": {
      "provider": "dashscope",
      "input_per_mtok": 0.05,
      "output_per_mtok": 0.2
    },
    "qwen-turbo-2024-11-01": {
      "provider": "dashscope",
      "input_per_mtok": 0.05,
      "output_per_mtok": 0.2
    },
    "qwen-turbo-2025-04-28": {
      "provider": "dashscope",
      "input_per_mtok": 0.05,
      "output_per_mtok": 0.2
    },
    "qwen-turbo-latest": {
      "provider": "dashscope",
      "input_per_mtok": 0.05,
      "output_per_mtok": 0.2
    },
    "qwen/qwen-2.5-72b-instruct": {
      "provider": "openrouter",
      "free": false
    },
    "qwen/qwen-2.5-7b-instruct": {
      "provider": "openrouter",
      "free": false
    },
    "qwen/qwen-2.5-coder-32b-instruct": {
      "provider": "openrouter",
      "input_per_mtok": 0.18,
      "output_per_mtok": 0.18,
      "free": false
    },
    "qwen/qwen-plus": {
      "provider": "openrouter",
      "free": false
    },
    "qwen/qwen-plus-2025-07-28": {
      "provider": "openrouter",
      "free": false
    },
    "qwen/qwen-plus-2025-07-28:thinking": {
      "provider": "openrouter",
      "free": false
    },
    "qwen/qwen-vl-plus": {
      "provider": "openrouter",
      "input_per_mtok": 0.21,
      "output_per_mtok": 0.63
    },
    "qwen/qwen2.5-vl-72b-instruct": {
      "provider": "openrouter",
      "free": false
    },
    "qwen/qwen3-14b": {
      "provider": "openrouter",
      "free": false
    },
    "qwen/qwen3-235b-a22b": {
      "provider": "openrouter",
      "free": false
    },
    "qwen/qwen3-235b-a22b-2507": {
      "provider": "openrouter",
      "input_per_mtok": 0.071,
      "output_per_mtok": 0.1,
      "free": false
    },
    "qwen/qwen3-235b-a22b-thinking-2507": {
      "provider": "openrouter",
      "input_per_mtok": 0.11,
      "output_per_mtok": 0.6,
      "free": false
    },
    "qwen/qwen3-30b-a3b": {
      "provider": "openrouter",
      "free": false
    },
    "qwen/qwen3-30b-a3b-instruct-2507": {
      "provider": "openrouter",
      "free": false
    },
    "qwen/qwen3-30b-a3b-thinking-2507": {
      "provider": "openrouter",
      "free": false
    },
    "qwen/qwen3-32b": {
      "provider": "openrouter",
      "free": false
    },
    "qwen/qwen3-8b": {
      "provider": "openrouter",
      "free": false
    },
    "qwen/qwen3-coder": {
      "provider": "openrouter",
      "input_per_mtok": 0.22,
      "output_per_mtok": 0.95,
      "free": false
    },
    "qwen/qwen3-coder-30b-a3b-instruct": {
      "provider": "openrouter",
      "free": false
    },
    "qwen/qwen3-coder-flash": {
      "provider": "openrouter",
      "free": false
    },
    "qwen/qwen3-coder-next": {
      "provider": "openrouter",
      "free": false
    },
    "qwen/qwen3-coder-plus": {
      "provider": "openrouter",
      "input_per_mtok": 1.0,
      "output_per_mtok": 5.0,
      "free": false
    },
    "qwen/qwen3-coder:free": {
      "provider": "openrouter",
      "free": true
    },
    "qwen/qwen3-max": {
      "provider": "openrouter",
      "free": false
    },
    "qwen/qwen3-max-thinking": {
      "provider": "openrouter",
      "free": false
    },
    "qwen/qwen3-next-80b-a3b-instruct": {
      "provider": "openrouter",
      "free": false
    },
    "qwen/qwen3-next-80b-a3b-instruct:free": {
      "provider": "openrouter",
      "free": true
    },
    "qwen/qwen3-next-80b-a3b-thinking": {
      "provider": "openrouter",
      "free": false
    },
    "qwen/qwen3-vl-235b-a22b-instruct": {
      "provider": "openrouter",
      "free": false
    },
    "qwen/qwen3-vl-235b-a22b-thinking": {
      "provider": "openrouter",
      "free": false
    },
    "qwen/qwen3-vl-30b-a3b-instruct": {
      "provider": "openrouter",
      "free": false
    },
    "qwen/qwen3-vl-30b-a3b-thinking": {
      "provider": "openrouter",
      "free": false
    },
    "qwen/qwen3-vl-32b-instruct": {
      "provider": "openrouter",
      "free": false
    },
    "qwen/qwen3-vl-8b-instruct": {
      "provider": "openrouter",
      "free": false
    },
    "qwen/qwen3-vl-8b-thinking": {
      "provider": "openrouter",
      "free": false
    },
    "qwen/qwen3.5-122b-a10b": {
      "provider": "openrouter",
      "input_per_mtok": 0.4,
      "output_per_mtok": 2.0,
      "free": false
    },
    "qwen/qwen3.5-27b": {
      "provider": "openrouter",
      "input_per_mtok": 0.3,
      "output_per_mtok": 2.4,
      "free": false
    },
    "qwen/qwen3.5-35b-a3b": {
      "provider": "openrouter",
      "input_per_mtok": 0.25,
      "output_per_mtok": 2.0,
      "free": false
    },
    "qwen/qwen3.5-397b-a17b": {
      "provider": "openrouter",
      "input_per_mtok": 0.6,
      "output_per_mtok": 3.6,
      "free": false
    },
    "qwen/qwen3.5-9b": {
      "provider": "openrouter",
      "free": false
    },
    "qwen/qwen3.5-flash-02-23": {
      "provider": "openrouter",
      "input_per_mtok": 0.1,
      "output_per_mtok": 0.4,
      "free": false
    },
    "qwen/qwen3.5-plus-02-15": {
      "provider": "openrouter",
      "input_per_mtok": 0.4,
      "output_per_mtok": 2.4,
      "free": false
    },
    "qwen/qwen3.5-plus-20260420": {
      "provider": "openrouter",
      "free": false
    },
    "qwen/qwen3.6-27b": {
      "provider": "openrouter",
      "free": false
    },
    "qwen/qwen3.6-35b-a3b": {
      "provider": "openrouter",
      "free": false
    },
    "qwen/qwen3.6-flash": {
      "provider": "openrouter",
      "free": false
    },
    "qwen/qwen3.6-max-preview": {
      "provider": "openrouter",
      "free": false
    },
    "qwen/qwen3.6-plus": {
      "provider": "openrouter",
      "input_per_mtok": 0.325,
      "output_per_mtok": 1.95,
      "free": false
    },
    "qwen3-next-80b-a3b-instruct": {
      "provider": "dashscope",
      "input_per_mtok": 0.15,
      "output_per_mtok": 1.2
    },
    "qwen3-next-80b-a3b-thinking": {
      "provider": "dashscope",
      "input_per_mtok": 0.15,
      "output_per_mtok": 1.2
    },
    "qwq-plus": {
      "provider": "dashscope",
      "input_per_mtok": 0.8,
      "output_per_mtok": 2.4
    },
    "rekaai/reka-edge": {
      "provider": "openrouter",
      "free": false
    },
    "rekaai/reka-flash-3": {
      "provider": "openrouter",
      "free": false
    },
    "relace/relace-apply-3": {
      "provider": "openrouter",
      "free": false
    },
    "relace/relace-search": {
      "provider": "openrouter",
      "free": false
    },
    "sao10k/l3-euryale-70b": {
      "provider": "openrouter",
      "free": false
    },
    "sao10k/l3-lunaris-8b": {
      "provider": "openrouter",
      "free": false
    },
    "sao10k/l3.1-70b-hanami-x1": {
      "provider": "openrouter",
      "free": false
    },
    "sao10k/l3.1-euryale-70b": {
      "provider": "openrouter",
      "free": false
    },
    "sao10k/l3.3-euryale-70b": {
      "provider": "openrouter",
      "free": false
    },
    "stepfun/step-3.5-flash": {
      "provider": "openrouter",
      "free": false
    },
    "switchpoint/router": {
      "provider": "openrouter",
      "input_per_mtok": 0.85,
      "output_per_mtok": 3.4,
      "free": false
    },
    "tencent/hunyuan-a13b-instruct": {
      "provider": "openrouter",
      "free": false
    },
    "tencent/hy3-preview": {
      "provider": "openrouter",
      "free": false
    },
    "thedrummer/cydonia-24b-v4.1": {
      "provider": "openrouter",
      "free": false
    },
    "thedrummer/rocinante-12b": {
      "provider": "openrouter",
      "free": false
    },
    "thedrummer/skyfall-36b-v2": {
      "provider": "openrouter",
      "free": false
    },
    "thedrummer/unslopnemo-12b": {
      "provider": "openrouter",
      "free": false
    },
    "undi95/remm-slerp-l2-13b": {
      "provider": "openrouter",
      "input_per_mtok": 1.875,
      "output_per_mtok": 1.875,
      "free": false
    },
    "upstage/solar-pro-3": {
      "provider": "openrouter",
      "free": false
    },
    "writer/palmyra-x5": {
      "provider": "openrouter",
      "free": false
    },
    "x-ai/grok-3": {
      "provider": "openrouter",
      "free": false
    },
    "x-ai/grok-3-beta": {
      "provider": "openrouter",
      "free": false
    },
    "x-ai/grok-3-mini": {
      "provider": "openrouter",
      "free": false
    },
    "x-ai/grok-3-mini-beta": {
      "provider": "openrouter",
      "free": false
    },
    "x-ai/grok-4": {
      "provider": "openrouter",
      "input_per_mtok": 3.0,
      "output_per_mtok": 15.0,
      "free": false
    },
    "x-ai/grok-4-fast": {
      "provider": "openrouter",
      "free": false
    },
    "x-ai/grok-4.1-fast": {
      "provider": "openrouter",
      "free": false
    },
    "x-ai/grok-4.20": {
      "provider": "openrouter",
      "free": false
    },
    "x-ai/grok-4.20-multi-agent": {
      "provider": "openrouter",
      "free": false
    },
    "x-ai/grok-4.3": {
      "provider": "openrouter",
      "free": false
    },
    "x-ai/grok-code-fast-1": {
      "provider": "openrouter",
      "free": false
    },
    "xiaomi/mimo-v2-flash": {
      "provider": "openrouter",
      "input_per_mtok": 0.09,
      "output_per_mtok": 0.29,
      "cached_input_per_mtok": 0.0,
      "cache_creation_per_mtok": 0.0,
      "free": false
    },
    "xiaomi/mimo-v2-omni": {
      "provider": "openrouter",
      "free": false
    },
    "xiaomi/mimo-v2-pro": {
      "provider": "openrouter",
      "free": false
    },
    "xiaomi/mimo-v2.5": {
      "provider": "openrouter",
      "free": false
    },
    "xiaomi/mimo-v2.5-pro": {
      "provider": "openrouter",
      "free": false
    },
    "z-ai/glm-4-32b": {
      "provider": "openrouter",
      "free": false
    },
    "z-ai/glm-4.5": {
      "provider": "openrouter",
      "free": false
    },
    "z-ai/glm-4.5-air": {
      "provider": "openrouter",
      "free": false
    },
    "z-ai/glm-4.5-air:free": {
      "provider": "openrouter",
      "free": true
    },
    "z-ai/glm-4.5v": {
      "provider": "openrouter",
      "free": false
    },
    "z-ai/glm-4.6": {
      "provider": "openrouter",
      "input_per_mtok": 0.4,
      "output_per_mtok": 1.75,
      "free": false
    },
    "z-ai/glm-4.6v": {
      "provider": "openrouter",
      "free": false
    },
    "z-ai/glm-4.7": {
      "provider": "openrouter",
      "input_per_mtok": 0.4,
      "output_per_mtok": 1.5,
      "cached_input_per_mtok": 0.0,
      "cache_creation_per_mtok": 0.0,
      "free": false
    },
    "z-ai/glm-4.7-flash": {
      "provider": "openrouter",
      "input_per_mtok": 0.07,
      "output_per_mtok": 0.4,
      "cached_input_per_mtok": 0.0,
      "cache_creation_per_mtok": 0.0,
      "free": false
    },
    "z-ai/glm-5": {
      "provider": "openrouter",
      "input_per_mtok": 0.8,
      "output_per_mtok": 2.56,
      "free": false
    },
    "z-ai/glm-5-turbo": {
      "provider": "openrouter",
      "free": false
    },
    "z-ai/glm-5.1": {
      "provider": "openrouter",
      "free": false
    },
    "z-ai/glm-5v-turbo": {
      "provider": "openrouter",
      "free": false
    },
    "zai/glm-4.5": {
      "provider": "zai",
      "input_per_mtok": 0.6,
      "output_per_mtok": 2.2
    },
    "zai/glm-4.5-air": {
      "provider": "zai",
      "input_per_mtok": 0.2,
      "output_per_mtok": 1.1
    },
    "zai/glm-4.6": {
      "provider": "zai",
      "input_per_mtok": 0.6,
      "output_per_mtok": 2.2,
      "cached_input_per_mtok": 0.11,
      "cache_creation_per_mtok": 0
    },
    "~anthropic/claude-haiku-latest": {
      "provider": "openrouter",
      "free": false
    },
    "~anthropic/claude-opus-latest": {
      "provider": "openrouter",
      "free": false
    },
    "~anthropic/claude-sonnet-latest": {
      "provider": "openrouter",
      "free": false
    },
    "~google/gemini-flash-latest": {
      "provider": "openrouter",
      "input_per_mtok": 0.3,
      "output_per_mtok": 2.5,
      "cached_input_per_mtok": 0.03,
      "free": false
    },
    "~google/gemini-pro-latest": {
      "provider": "openrouter",
      "input_per_mtok": 1.25,
      "output_per_mtok": 10.0,
      "cached_input_per_mtok": 0.125,
      "free": false
    },
    "~moonshotai/kimi-latest": {
      "provider": "openrouter",
      "free": false
    },
    "~openai/gpt-latest": {
      "provider": "openrouter",
      "free": false
    },
    "~openai/gpt-mini-latest": {
      "provider": "openrouter",
      "free": false
    }
  }
} as const;
